// Code generated by hertz generator.

package math

import (
	"fmt"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	gateway "orbital_demo/biz/gateway"
	math "orbital_demo/biz/model/math"
)

// Add .
// @router /math/add [POST]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math.AddRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	fmt.Println("Hertz is running for math")
	gateway.GenericCall("math", "add", ctx, c)
}

// Subtract .
// @router /math/subtract [POST]
func Subtract(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math.SubtractRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	fmt.Println("Hertz is running for math")
	gateway.GenericCall("math", "subtract", ctx, c)
}

// Multiply .
// @router /math/multiply [POST]
func Multiply(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math.MultiplyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	fmt.Println("Hertz is running for math")
	gateway.GenericCall("math", "multiply", ctx, c)
}

// Divide .
// @router /math/divide [POST]
func Divide(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math.DivideRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	fmt.Println("Hertz is running for math")
	gateway.GenericCall("math", "divide", ctx, c)
}
