// Code generated by Kitex v0.6.1. DO NOT EDIT.

package mathsvc

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	math "orbital_demo/kitex_gen/math"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, req *math.AddRequest, callOptions ...callopt.Option) (r *math.AddResponse, err error)
	Subtract(ctx context.Context, req *math.SubtractRequest, callOptions ...callopt.Option) (r *math.SubtractResponse, err error)
	Multiply(ctx context.Context, req *math.MultiplyRequest, callOptions ...callopt.Option) (r *math.MultiplyResponse, err error)
	Divide(ctx context.Context, req *math.DivideRequest, callOptions ...callopt.Option) (r *math.DivideResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMathSvcClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMathSvcClient struct {
	*kClient
}

func (p *kMathSvcClient) Add(ctx context.Context, req *math.AddRequest, callOptions ...callopt.Option) (r *math.AddResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, req)
}

func (p *kMathSvcClient) Subtract(ctx context.Context, req *math.SubtractRequest, callOptions ...callopt.Option) (r *math.SubtractResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Subtract(ctx, req)
}

func (p *kMathSvcClient) Multiply(ctx context.Context, req *math.MultiplyRequest, callOptions ...callopt.Option) (r *math.MultiplyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Multiply(ctx, req)
}

func (p *kMathSvcClient) Divide(ctx context.Context, req *math.DivideRequest, callOptions ...callopt.Option) (r *math.DivideResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Divide(ctx, req)
}
