// Code generated by Kitex v0.6.1. DO NOT EDIT.

package mathsvc

import (
	server "github.com/cloudwego/kitex/server"
	math "orbital_demo/kitex_gen/math"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler math.MathSvc, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
