// Code generated by Kitex v0.6.1. DO NOT EDIT.
package mathsvc

import (
	server "github.com/cloudwego/kitex/server"
	math "orbital_demo/kitex_gen/math"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler math.MathSvc, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
