// Code generated by hertz generator.

package echo

import (
	"context"
	"fmt"

	gateway "orbital_demo/biz/gateway"
	echo "orbital_demo/biz/model/echo"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Echo .
// @router /echo/echo [POST]
func Echo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req echo.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println("Hertz is running for echo")
	gateway.GenericCall("echo", "echo", ctx, c)
}
