// Code generated by hertz generator.

package math

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _divideMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _multiplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _subtractMw() []app.HandlerFunc {
	// your code...
	return nil
}
